//tealium universal tag - utag.14 ut4.0.201502100607, Copyright 2015 Tealium.com Inc. All Rights Reserved.
try{if(!utag.libloader){utag.libloader=function(src,handler,a,b){a=document;b=a.createElement('script');b.language='javascript';b.type='text/javascript';b.src=src;if(typeof handler=='function'){b.handlerFlag=0;b.onreadystatechange=function(){if((this.readyState=='complete'||this.readyState=='loaded')&&!b.handlerFlag){b.handlerFlag=1;handler()}};b.onload=function(){if(!b.handlerFlag){b.handlerFlag=1;handler()}};a.getElementsByTagName('head')[0].appendChild(b)}}};(function(id,loader,u){u=utag.o[loader].sender[id]={};u.ev={'view':1};u.map={};u.extend=[function(a,b){try{if(1){b['io_path']=b['js_page.s.pageName'];b['io_country']=b['country_code'];b['io_language']=b['language_code'];b['io_storecode']=b['site_id'];b['io_storecodedescription']=b['dom.title'];b['io_referrer']=b['dom.referrer']}}catch(e){utag.DB(e)}},function(a,b){var app=window.LENOVO=(window.LENOVO||{}),self=app.IGNITIONONE={io_loop:0,io_path:b.io_path,io_timeout:null,init:function(){self.io_timeout=null;if(!self.io_path||self.io_path.indexOf("=")!==-1){if(!!window.s&&typeof window.s.dynComp=="function")window.s.dynComp("u");self.io_path=("pageName"in window.s)?window.s.pageName:"";}
self.addIO();},addIO:function(){if(typeof self.io_path==="string"&&self.io_path!==""){var h="com-lenovo.netmng.com";var t=window.document.createElement("script");t.type="text/javascript";t.async=true;var p="https:"==window.document.location.protocol?"https://":"http://";t.src=p+h+"/?async=1"
+"&ref="+encodeURIComponent(b.io_referrer)
+"&path="+encodeURIComponent(self.io_path)
+"&sc="+encodeURIComponent(b.io_country)
+"&sl="+encodeURIComponent(b.io_language)
+"&ssc="+encodeURIComponent(b.io_storecode)
+"&sscd="+encodeURIComponent(b.io_storecodedescription);var sc=window.document.getElementsByTagName("script")[0];sc.parentNode.insertBefore(t,sc);if(!!window.jQuery){if($(".tabs").length>0){self.trackTabs();}}}else{self.io_loop++;if(self.io_loop<=5){self.io_path=(!!window.s&&"pageName"in window.s)?window.s.pageName:"";self.io_timeout=setTimeout(self.init,500);}else{self.io_path="*"+window.location.pathname+window.location.search;self.io_timeout=setTimeout(self.init,500);}}},trackTabs:function(){$(document).find(".tabs").children(".tab, .tab-item").find("a").on("click.nmpush",function(e){var _href=(window.location.protocol+"//"+window.location.hostname+window.location.pathname+window.location.hash),_temp=["trackurl",_href];window._nm=(window._nm||[]);window._nm.push(_temp);});}};self.init();}];u.send=function(a,b,c,d,e,f){if(u.ev[a]||typeof u.ev.all!="undefined"){var data={};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};for(d in utag.loader.GV(u.map)){if(typeof b[d]!='undefined'){e=u.map[d].split(',');for(f=0;f<e.length;f++){data[e[f]]=b[d]}}}
}};try{utag.o[loader].loader.LOAD(id)}catch(e){utag.loader.LOAD(id)}})('14','lenovo.main');}catch(e){}
