//tealium universal tag - utag.84 ut4.0.201410291441, Copyright 2014 Tealium.com Inc. All Rights Reserved.
var addthis_config={};try{(function(id,loader,u){try{u=utag.o[loader].sender[id]={}}catch(e){u=utag.sender[id]};u.ev={'view':1};u.qsp_delim="&";u.pubid="ra-5048b50a00f5671e";u.pxid="";u.dnt="";u.ev_="";u.base_url="//s7.addthis.com/js/250/addthis_widget.js#";u.map={};u.extend=[function(a,b,c,d,e,f,g){d=b['country_code'];if(typeof d=='undefined')return;c=[{'gb|uk':'ra-53bde1602b387c7c'}];var m=false;for(e=0;e<c.length;e++){for(f in c[e]){if(d==f){b['addthis_profileid']=c[e][f];m=true};};if(m)break};if(!m)b['addthis_profileid']='ra-5048b50a00f5671e';},function(a,b,c,d,e,f,g){d=b['country_code'];if(typeof d=='undefined')return;c=[{'gb|uk':'awesm'}];var m=false;for(e=0;e<c.length;e++){for(f in c[e]){g=new RegExp(f,'i');if(g.test(d)){b['addthis_shortener']=c[e][f];m=true};};if(m)break};if(!m)b['addthis_shortener']='bitly';},function(a,b){function createAddThisShare(sh,sp){var as;as=window.addthis_share||{};sp=typeof sp==="string"?sp.split(","):[];if(sp.length>0){as.url_transforms={};as.url_transforms.shorten={};for(var i=0;i<sp.length;i++){var k=sp[i];as.url_transforms.shorten[k]=sh;}
as.shorteners={};as.shorteners[sh]={};if(sh=="awesm"){as.shorteners[sh].key="709e1e1a43f8cbe20ba62ac5191fff223ea99ba79e0ffaee78eb05708dcb1c3b";}
window.addthis_share=as;}}
try{createAddThisShare(b["addthis_shortener"],b["meta.socialshareplatform"]);}catch(error){if(!!window.console){console.warn("Could not create AddThis Share object (addthis_share).");console.error(error);}}},function(a,b){function createAddThisMarkup(cc,pt,sp){var at,c,cid;if(typeof cc!=="string")cc=null;if(typeof pt!=="string")pt=null;sp=typeof sp==="string"?sp.split(","):[];if(sp.length>0){at=document.createElement("div");at.className="addthis_toolbox addthis_default_style addthis_32x32_style";for(var i=0;i<sp.length;i++){var a=document.createElement("a");a.className="addthis_button_"+sp[i];at.appendChild(a);}
wrap=document.createElement("div");wrap.className="cta-group-share addthis-subseries";if(cc!=null)wrap.className+=" addthis-"+cc;if(pt!=null)wrap.className+=" addthis-"+pt;wrap.appendChild(at);cid="addThis_CSS";if(!document.getElementById(cid)){c=document.createElement("link");c.id=cid;c.rel="stylesheet";c.type="text/css";c.href="/ISS_Static/WW/css/themes/owv2/modules/addThis.css";}
if(document.getElementsByClassName("cta")[0]!=null){if(c!=null)document.getElementsByTagName("head")[0].appendChild(c);if(document.getElementsByClassName("cta-group-reviews")[0]!=null){document.getElementsByClassName("cta-group-reviews")[0].appendChild(wrap);}else{document.getElementsByClassName("cta")[0].appendChild(wrap);}}}}
try{createAddThisMarkup(b.country_code,b.sub_page_type,b["meta.socialshareplatform"]);}catch(error){if(!!window.console){console.warn("Could not generate AddThis markup for injection.");console.error(error);}}}];u.send=function(a,b,c,d,e,f,g){if(u.ev[a]||typeof u.ev.all!="undefined"){for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};c=[];g={};for(d in utag.loader.GV(u.map)){if(typeof b[d]!="undefined"&&b[d]!=""){e=u.map[d].split(",");for(f=0;f<e.length;f++){g[e[f]]=b[d];}}}
if(typeof g.ev=="undefined"&&u.ev_!=""){g.ev=u.ev_};if(typeof g.pubid=="undefined"&&u.pubid!=""){g.pubid=u.pubid};if(typeof g.pxid=="undefined"&&u.pxid!=""){g.pxid=u.pxid};addthis_config.pubid=g.pubid;e=[];for(d in g){if(d=="pxid"||d=="ev"){e.push(d+"="+g[d]);}else{c.push(d+"="+g[d]);}}
if(e.length>0){c.push("adev="+encodeURIComponent(e.join(',')));}
if(u.dnt!=""){c.push("dnt="+u.dnt)};u.s=document.getElementsByTagName("script")[0];u.scr=document.createElement("script");u.scr.type="text/javascript";u.scr.src=u.base_url+c.join(u.qsp_delim);u.s.parentNode.insertBefore(u.scr,u.s);}}
try{utag.o[loader].loader.LOAD(id)}catch(e){utag.loader.LOAD(id)}})('84','lenovo.main');}catch(e){}
