/* Copyright (c) 2005-2014 Oracle and/or its affiliates. Contains software licensed under the MIT license. Removal of this notice is prohibited. Full attribution and licensing at: http://recmanager.atg.com/api/license.html */
(function(){var y,l=document,w=window,u=w.ATGSvcs,z=u.dom.DIV,G=u.Selector,v=u.pagepeek,A=u.util,r=A.each,H=A.paramToURL,B=navigator.userAgent.match(/(?:msie |trident.*rv:)(\d+)/i)?+RegExp.$1:0,C=B&&9>B,I=[],J=[],D=[],s,x,E=function(a,e){var b=w.frames,g,j=b.length;for(e||(e=[]);j--;){g=b[j];try{var c=g.ATGSvcs,f=c&&c.pagepeek,d=f&&c.cobrowse;f&&f.active&&(e.push(g),a&&d&&d.getCBFrames(a,e))}catch(p){}}return e},L=function(){s="z"+ +new Date;var a,e,b,g=K(l);a=z();var j={fs_level:-2,pagepeek:1,revision:1,
accountid:u.CFG.uoid,visitorid:u.visitorId(),estara_fsguid:w.eStara_fsguid,location:location.href.slice(0,1E3),cs:l.characterSet||l.charset,clientwidth:l.documentElement.clientWidth||l.body.clientWidth},j=H(v.host+"/fs/cbgs.php",j),c=function(){if(!b)try{b=l.createElement(C?'<iframe name="'+s+'">':"iframe")}catch(d){b=l.createElement("iframe")}if(b){var a=b.style;b.setAttribute("src","javascript:void 0;");b.setAttribute("scrolling","no");b.setAttribute("frameBorder","0");b.setAttribute("id",s);b.setAttribute("name",
s);a.border=a.width=a.height=0;a.display="none";l.body.appendChild(b);e=b&&(b.document||b.contentDocument)}};if(!y.ppForm){y.ppForm=x="ppForm"+s;b=c();if(!e&&(c(),!e))return;for(var c=E(1),f=c.length,d,p,k;f--;)d=c[f],k=d.ATGSvcs.cobrowse&&d.ATGSvcs.cobrowse.ppHTML,d=d.document,p=d.location.href,g+="\n\x3c!-- pagepeekstart:"+p+" --\x3e\n"+(k?k(d):"\x3c!-- pp.js not loaded --\x3e")+"\n\x3c!-- "+p+":pagepeekend --\x3e";if(8<=B){k=f=c="";var m;d="ABCDEFGHIJKLMNOPQRSTUVWXYZ";d+=d.toLowerCase()+"0123456789+/";
for(g=escape(encodeURI(g));g.charAt(+c)||f;d=g.charAt(c++)?d:"=")k+=d.charAt(63&(m=m<<8|g.charCodeAt(c-=!(f=f+2&7)))>>f);g="MSIE8"+k}a.innerHTML='<form id="'+x+'" action="'+j+"&pageid="+s+'" method="post" target="'+s+'"><input type="hidden" name="uploadsize" value="'+g.length+'"><input type="hidden" name="eStara_bigupload" value="'+g+'"></form>';e.body?e.body.appendChild(a):e.appendChild(a);(a=e.getElementById(x))&&a.submit();a=null}},K=function(a){for(var e=a.body,b,g=s?"\n\x3c!-- pagepeek master --\x3e\n":
"",j="",c=a.forms.length,f=function(a,b){a[b]="";a.hasAttribute&&a.hasAttribute(b)&&(a.setAttribute(b,""),a.removeAttribute(b,0))},d=z(),p=function(a,b){C&&(a="<p>pp</p>"+a);b&&(a=a.replace(/&/g,"&amp;"));d.innerHTML=a;for(var c=d.getElementsByTagName("script"),e=c.length;e--;)c[e].parentNode.removeChild(c[e]);b&&(r(d.getElementsByTagName("form"),function(a,b){b.action="#";f(b,"onsubmit")}),r(d.getElementsByTagName("a"),function(a,b){b.href="#";f(b,"onclick")}),r(d.getElementsByTagName("option"),
function(a,b){f(b,"selected")}),r(["input","textarea","select","button"],function(a,b){r(d.getElementsByTagName(b),function(a,b){f(b,"onchange");f(b,"onclick");var c=b.type;"checkbox"==c||"radio"==c?(b.checked=!1,f(b,"checked")):"selectedIndex"==c?b.selectedIndex=-1:"textarea"==c?b.innerHTML="":f(b,"value")})}));a=d.innerHTML;C&&(a=a.replace(/<p>pp<\/p>/i,""));return a},k=0,m=v.rules.length;k<m;k++){var n=v.rules[k],l=n[0],q=n[1],t=n[2];l.compare=l.compare||"r";"r"==l.compare?(n=A.makeRegExp(l.select,
l),l.trim&&(n.trim=1),l["case"]&&(n["case"]=1)):n=l;n=[t,n];("hide"==q?J:I).push(n);"hide"==q&&"id"==t&&D.push(n)}r(a.forms,function(b,a){r(a.elements,function(a,c){if(c){var e=c.type,d,h=null;if(!F(c,J)){d=F(c,I);if("radio"==e)!d&&c.checked&&(h=c.value);else if("select-one"==e)d||(h=c.selectedIndex);else if("checkbox"==e)!d&&c.checked&&(h=!0);else if(null!=c.value&&(h=c.value,"password"==e||d))h=Array(1+h.length).join("*");null!=h&&("string"==typeof h&&(h=h.replace(/\r/g,"\\r"),h=h.replace(/\n/g,
"\\n"),h=h.replace(/\\/g,"\\\\"),h=h.replace(/'/g,"\\'"),h="'"+h+"'"),j+="\npp_set_element("+b+","+a+","+h+");")}}})});if(c){k=[];for(m=0;m<c;m++)k.push(a.forms[m].length);j="\nvar pp_ok=1;\nif (window['pp_check_forms']) pp_ok=pp_check_forms(["+k+"]);\nif (pp_ok) {\n"+j+"\n}"}g+="<script>\nfunction atg_pp_loaded() { "+j+"\nif (window['pp_load_blocker']) pp_load_blocker();\n}";"undefined"!=typeof a.compatmode&&"BackCompat"!=a.compatMode&&(g+="\nvar eStara_setdoctype=1;");b=e.innerHTML;D.length&&r(G("*[id]"),
function(a,c){if(F(c,D)){var d=b,e=[""],f=0,g="",h,j=function(b,a){var c,d;b&&(1==b.nodeType&&(d=b.nodeName.toLowerCase(),"form"==d?(e[++f]="<form>",c=1):/^(?:select|input|button|textarea)/.test(d)&&(e[f]+='<input type="hidden" />'),j(b.firstChild,1)),c&&(e[f]+="</form>"),a&&j(b.nextSibling,1))};c?(c.getClientRects&&r(c.getClientRects(),function(b,a){var c=parseInt(a.width||a.right-a.left,10),d=parseInt(a.height||a.bottom-a.top,10);d&&c&&(g+='<img style="border:0;padding:0;margin:0" width="'+c+'" height="'+
d+'" src="/fs/clear.gif" />')}),j(c),c.outerHTML?h=c.outerHTML:(h=z("div"),h.appendChild(c.cloneNode(!0)),h=h.innerHTML.replace(/^div/,"")),b=d.replace(h,g+e.join(""))):b=d}});b=p(b,1);a=G("head");e="<head>"+(a.length?p(a[0].innerHTML):"")+"</head><body"+(e.className?' class="'+e.className+'"':"")+(e.id?' id="'+e.id+'"':"")+">";a=b;p=E(0);c=p.length;k=v.host;for(k.match("/fs/cbb.php")||(k+=(k.match("/$")?"":"/")+"/fs/cbb.php");c--;)if(m=p[c],q=m.frameElement&&m.frameElement.attributes)if(t=q.name&&
q.name.value,q=q.src&&q.src.value||"",void 0!==t&&!q.match("/fs/cbb.php")&&(t=a.match(RegExp("<iframe[^>]+?name=(?:s|'|\")?"+t+"[^>]*?>","im"))))m=H(k,{url:m.document.location.href,pageid:s,estara_fsguid:w.eStara_fsguid}),a=a.replace(t[0],t[0].replace(q,m));return(e+a+g+"\x3c/script></body>").replace(/"/g,"%!22")},F=function(a,e){for(var b=0,g=e.length;b<g;b++){var j=a.getAttribute(e[b][0])||"",c=e[b][1],f,d=c.compare;c.trim&&(j=j.replace(/^\s+|\s+$/g,""));if(""!==j&&(c["case"]||(j=j.toLowerCase()),
"="==d?c.select==j&&(f=1):"~"==d?~j.indexOf(c.select)&&(f=1):c.test(j)&&(f=1),f))return 1}};u.cobrowse=y={uploadPP:L,ppForm:x,ppHTML:K,getCBFrames:E};v.launch&&L()})();

