//tealium universal tag - utag.87 ut4.0.201506261821, Copyright 2015 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={};u.extend=[function(a,b){try{window.ATGSvcs={'eeid':200106300809};if(window.jQuery&&!window.jQuery.oracleLoader)
{jQuery.oracleLoader=function(url,options)
{options=$.extend(options||{},{dataType:"script",cache:true,url:url,success:function(data){if(options.cb){options.cb(data);}}});return jQuery.ajax(options);};}
function oracleEECB()
{window.ATGSvcs.ESTARA_HOST="as00.estara.com";(function(){var l='lenovo.custhelp.com',d=document,ss='script',s=d.getElementsByTagName(ss)[0];function r(u){var rn=d.createElement(ss);rn.type='text/javascript';rn.defer=rn.async=!0;rn.src="https://"+l+u;s.parentNode.insertBefore(rn,s);}
r('/rnt/rnw/javascript/vs/1/vsapi.js');r('/vs/1/vsopts.js');})();}
if(location.href.indexOf("checkout.")==-1)
{$.oracleLoader("//static.atgsvcs.com/js/atgsvcs.js",{"cb":oracleEECB});}}catch(e){if(window.console){console.log(e);}}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
}};utag.o[loader].loader.LOAD(id);})("87","lenovo.ag");}catch(error){utag.DB(error);}
