//tealium universal tag - utag.82 ut4.0.201411211923, Copyright 2014 Tealium.com Inc. All Rights Reserved.
if(typeof utag.ut=="undefined"){utag.ut={};}
utag.ut.libloader2=function(o,a,b,c,l){a=document;b=a.createElement('script');b.language='javascript';b.type='text/javascript';b.async=true;b.src=o.src;if(o.id){b.id=o.id}
if(typeof o.cb=='function'){b.hFlag=0;b.onreadystatechange=function(){if((this.readyState=='complete'||this.readyState=='loaded')&&!b.hFlag){b.hFlag=1;o.cb();}};b.onload=function(){if(!b.hFlag){b.hFlag=1;o.cb();}};}
l=o.loc||'head';c=a.getElementsByTagName(l)[0];if(c){if(l=='script'){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}
utag.DB("Attach to "+l+": "+o.src);}};try{(function(id,loader){var u=utag.o[loader].sender[id]={};u.ev={'view':1};u.initialized=false;u.map={};u.extend=[function(a,b,c,d,e,f,g){d=b['country_code'];if(typeof d=='undefined')return;c=[{'ca':'invite.ca.lenovo.com'},{'gb':'invite.gb.lenovo.com'},{'fr':'invite.fr.lenovo.com'},{'de':'invite.de.lenovo.com'},{'at':'invite.at.lenovo.com'},{'ch':'invite.ch.lenovo.com'},{'dk':'invite.dk.lenovo.com'},{'nl':'invite.nl.lenovo.com'},{'br':'invite.br.lenovo.com'},{'mx':'invite.mx.lenovo.com'},{'co':'invite.co.lenovo.com'},{'ar':'invite.ar.lenovo.com'},{'in':'invite.in.lenovo.com'},{'jp':'invite.jp.lenovo.com'},{'au':'invite.au.lenovo.com'},{'nz':'invite.nz.lenovo.com'},{'ru':'invite.ru.lenovo.com'},{'kr':'invite.kr.lenovo.com'},{'ie':'invite.ie.lenovo.com'},{'us':'invite.us.lenovo.com'},{'hk':'invite.hk.lenovo.com'},{'sg':'invite.sg.lenovo.com'}];var m=false;for(e=0;e<c.length;e++){for(f in c[e]){if(d==f){b['oo_fakedomain']=c[e][f];m=true};};if(m)break};if(!m)b['oo_fakedomain']='invite.XX.lenovo.com';},function(a,b,c,d,e,f,g){d=b['language_code'];if(typeof d=='undefined')return;c=[{'en':'/ISS_Static/WW/tms/opinionlab/5.8.1/en/'},{'fr':'/ISS_Static/WW/tms/opinionlab/5.8.1/fr/'},{'de':'/ISS_Static/WW/tms/opinionlab/5.8.1/de/'},{'pt':'/ISS_Static/WW/tms/opinionlab/5.8.1/pt/'},{'ru':'/ISS_Static/WW/tms/opinionlab/5.8.1/ru/'},{'es':'/ISS_Static/WW/tms/opinionlab/5.8.1/es/'},{'ja':'/ISS_Static/WW/tms/opinionlab/5.8.1/ja/'},{'ko':'/ISS_Static/WW/tms/opinionlab/5.8.1/ko/'}];var m=false;for(e=0;e<c.length;e++){for(f in c[e]){if(d==f){b['oo_exit_asset_path']=c[e][f];m=true};};if(m)break};if(!m)b['oo_exit_asset_path']='/ISS_Static/WW/tms/opinionlab/5.8.1/';},function(a,b){function mobileInit(){'use strict';window.oo_mobile_invite=new OOo.Ocode({clickTalePID:(typeof window.ClickTaleGetPID==='function'?window.ClickTaleGetPID():303),referrerRewrite:{searchPattern:/:\/\/[^\/]*/,replacePattern:'://'+b.oo_fakedomain}});window.oo_mobile_invite.show();}
function defaultInit(){'use strict';var _pagesHit=2,_respRate=30,_repromptT=7776000,_promptDelay=3,loc=window.location,hostname=loc.hostname,path=loc.pathname;if(!!window.OOo&&!OOo.Browser.isMobile){var rc='oo_inv_reprompt';if(hostname.search(/support/i)>-1){rc='oo_inv_support';}
if(b.io_popin){_respRate=0;}
if(b["qp.oo_popin"]=="true"){_repromptT=1;_respRate=100;_pagesHit=0;_promptDelay=0;}
if(typeof OOo.Invitation==="function"){window.oo_invite=new OOo.Invitation({clickTalePID:(typeof window.ClickTaleGetPID==='function'?window.ClickTaleGetPID():303),pathToAssets:(b.oo_exit_asset_path!=null?('//'+hostname+b.oo_exit_asset_path):('//'+hostname+'/ISS_Static/WW/tms/opinionlab/5.8.1/')),responseRate:_respRate,repromptTime:_repromptT,pagesHit:_pagesHit,promptDelay:_promptDelay,neverShowAgainButton:true,referrerRewrite:{searchPattern:/:\/\/[^\/]*/,replacePattern:'://'+b.oo_fakedomain},customVariables:{referringPage:loc.href},repromptCookie:rc});}}}
function ready(fn){'use strict';if(document.readyState==='complete'){return fn;}
if(window.addEventListener){window.addEventListener('load',fn,false);}else if(window.attachEvent){window.attachEvent('onload',fn);}else{window.onload=fn;}}
try{ready(defaultInit);}catch(error){throw new Error("\"Opinion Lab - Exit Survey\" setup encountered an error.");}}];u.send=function(a,b){if(u.ev[a]||typeof u.ev.all!="undefined"){var c,d,e,f,i;u.data={};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};for(d in utag.loader.GV(u.map)){if(typeof b[d]!='undefined'){e=u.map[d].split(',');for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
}};utag.o[loader].loader.LOAD(id);})('82','lenovo.main');}catch(e){}
